theme: ./src

siteConfig:
  title: Victor Berland
  url: https://victorberland.com
  author: Victor Berland
  email: vb@victorberland.com
  description: Victor Berland

themeConfig:
  nav:
    - text: App
      link: /app.html
    - text: Lab
      link: /lab.html
    - text: Info
      link: /victor.html
  social:
    twitter: _saberjs
    github: egoist
    rss: true

permalinks:
  post: /:slug.html

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      # atomFeed: true
      rss2Feed: true
